AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  hackthon-backend:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::152115620306:role/LambdaDynamoRole'
      Runtime: python3.7
      Timeout: 3
